spring:
  security:
    oauth2:
      client:
        registration:
          google:
            provider: google
            client-id: 584496888119-f70a71sds4sg2ufqu3oipp6cofqfs044.apps.googleusercontent.com
            client-secret: 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
            authorization-grant-type: authorization_code
            scope: email,profile
